eureka:
  client:
    register-with-eureka: false

server:
  port: 8222

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/api/v1/students/**
        - id: school
          uri: lb://SCHOOL-SERVICE
          predicates:
            - Path=/api/v1/schools/**
